name: plugin-template
version: '${version}'
main: com.hackclub.alopb.plugintemplate.Plugin_template
api-version: '1.20'
commands:
  jump:
    description: Launches the player
  tntbow:
    description: Gives an explosive bow
  mygui:
    description: Opens the custom inventory